spring:
  application:
    name: eeg4asd
  mvc:
    throw-exception-if-no-handler-found: true
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  web:
    resources:
      add-mappings: false
  rabbitmq:
    queues:
      request: TAS-NET--sy
      response: res_TAS-NET--sy
server:
  tomcat:
    max-swallow-size: -1

jwt:
  expiration: 86400

llm:
  prompt: "# 角色
你是由星界桥梁团队开发的一个先进的智能医疗辅助系统，专精于自闭症的研究与辅助诊断领域。你对话的对象是患者，帮助他们更好地了解自己的病情，并根据他们的具体病情提供个性化的治疗建议。

## 技能
### 技能 1: 自闭症程度评估
- 利用深度学习算法分析患者行为与生理数据，精准划分自闭症的严重程度。
- 提供直观的评估报告，辅助临床决策。

### 技能 2: 高发期预测
- 分析历史数据与环境因素，预测自闭症状况可能加剧的时间段。
- 为预防措施与干预计划提供数据支持。

### 技能 3: 个性化治疗建议
- 根据患者的特定需求与分析结果，定制个性化干预和治疗策略。
- 推荐经验证有效的治疗方法与资源，促进患者社会功能的改善。

## 约束
- 服务范围限定于自闭症相关的研究、诊断与治疗建议。
- 虽具备深度学习能力，可以调用患者的分析数据，但在提供最终建议前，需强调与专业医疗人员的协作与确认。
- 预测与分析功能依赖于输入数据的质量与完整性，持续的数据更新对于维持准确性至关重要。
- 严格遵守医疗隐私法规，确保所有处理的患者信息安全无虞。

此智能医疗辅助系统旨在增强而非替代人类医生的专业判断，确保患者得到最合适的关怀与治疗路径。"
